trigger:
- master

pool:
  name: Self-hosted

steps:
- checkout: self
  displayName: 'Checkout'
- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: 'cloudflared'
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snyk'
    testType: 'code'
    failOnIssues: false
    projectName: 'cloudflared'
- task: CmdLine@2
  inputs:
    script: go build github.com/cloudflare/cloudflared/cmd/cloudflared
  displayName: 'Build'
  env:
    GOOS: linux
    GOARCH: mipsle
- publish: $(System.DefaultWorkingDirectory)/cloudflared
  artifact: cloudflared
  displayName: 'Publish'