name: Rebase Upstream

on:
  schedule:
    - cron: '0 0 * * 0' # every sunday at midnight
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 3  # greater than the number of commits you made
    - uses: imba-tjd/rebase-upstream-action@master
